
addons:
 apt:
   packages:
   - build-essential
   - libssl-dev
before_install:
- sudo apt-get update -qq
- which node
- nvm ls-remote
- nvm install 6.4.0
- node --version
install: ./scripts/install-dependencies.sh
script: ./scripts/build.sh
