sudo: required
language: node_js
  - "6.4.0"
env:
  DOCKER_COMPOSE_VERSION: 1.8.0
  NODE_VERSION: 6.4.0
addons:
 apt:
   packages:
   - build-essential
   - libssl-dev
before_install:
  - env
  - sudo apt-get update -qq
  - nvm install ${NODE_VERSION}
  - node --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker pull mhart/alpine-node:${NODE_VERSION}
install: ./scripts/install-dependencies.sh
script: ./scripts/build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
    docker push pdhar/travis;
    fi
