
addons:
 apt:
   packages:
   - gcc-4.8
   - g++-4.8
   - cmake
   - time
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq nodejs
- npm install -g gulp
- node --version
install: ./scripts/install-dependencies.sh
script: ./script/build.sh
